### PR TITLE
Refactor the library.

### PR DESCRIPTION
**Pull request by floitsch**
Refactor API.
Add most missing modbus functions.

### CODE REVIEW

**Comment by gregger2k** [comment]
Great work on the RS485/RTU driver. Your refactor greatly enhances the usability of the driver.
Could you please provide an example of a simple RS485 Modbus app? I have looked through the test code an it is difficult to follow for a toit newbie like me.

A Modbus RTU example that covers all steps necessary in one place. including setting up the libraries, UART pins, buadrate, parity, etc would be a big help in getting me started with the conversion from micropython.

One of the most challenging things in  converting to  toit is the lack of the large amout of example code and libraries that micropython or Arduino have available.

toit and it's users are making great progress in providing high quality drivers, like the Modbus and MQTT that I am most familiar with. No if we can get more people onboard toit ;-)

**Comment by floitsch** [comment]
I will try to add more examples.
In the meantime, have a look at the n4aia04 driver which uses modbus rtu.
It's not committed yet, but here is the branch that is under review: https://github.com/toitware/toit-n4aia04/tree/floitsch/20.driver
If that link doesn't work anymore, then the PR is probably already submitted, and you can just look here: https://github.com/toitware/toit-n4aia04/tree/main

**Comment by gregger2k** [comment]
Thanks.
I found the n4aia04 driver shortly after the example request. I believe there is enough detail in the driver and test code to get me going. I also ordered some n4aia04 boards for testing.

**Comment by gregger2k** [comment]
I have been testing the new refactored library with RTU support. Great work on the refactor, much cleaner now!
I have one issue though. It seems that there is a problem with the **holding.write_many** function call when using RTU.
The write_single works o.k. and the read_many works o.k. but the write_many hangs with a DEADLINE_EXCEDED error.

Using the latest jag release and your latest pull requests
```
[modbus] DEBUG: write_single {address: 50, value: 512}
[modbus] DEBUG: write_holding_registers {address: 50, registers: [142, 102, 144]}

******************************************************************************
Decoded by `jag monitor` <2.0.0-alpha.12>
******************************************************************************
EXCEPTION error.
DEADLINE_EXCEEDED
  0: __Monitor__.await         <sdk>\core\monitor_impl.toit:28:20
  1: Signal.wait_              <sdk>\monitor.toit:165:7
  2: Signal.wait.<block>       <sdk>\monitor.toit:138:5
  3: __Monitor__.locked_.<block> <sdk>\core\monitor_impl.toit:123:12
  4: __Monitor__.locked_       <sdk>\core\monitor_impl.toit:95:3
  5: Signal.wait               <sdk>\monitor.toit:136:3
  6: TransactionManager_.read  <pkg:pkg-modbus>\bus.toit:191:13
  7: Modbus.send_.<block>.<block> <pkg:pkg-modbus>\bus.toit:117:40
  8: Task_.with_deadline_.<block> <sdk>\core\task.toit:73:21
  9: Task_.with_deadline_      <sdk>\core\task.toit:67:3
 10: with_timeout              <sdk>\core\utils.toit:179:15
 11: with_timeout              <sdk>\core\utils.toit:171:10
 12: Modbus.send_.<block>      <pkg:pkg-modbus>\bus.toit:116:7
 13: Modbus.send_              <pkg:pkg-modbus>\bus.toit:108:3
 14: HoldingRegisters.write_many <pkg:pkg-modbus>\station.toit:254:19
 15: main                      rtu.toit:31:11
```
The Modbus simulator does not identify the function code 6, but it does on the read single.

One more unrelated question:
What is the best way to read a signed 16 int stored in a register?
You have functions for the 32 bit and float but not single..

Keep up the great work. I will working on porting my RTU stuff over.
I might even attempt a driver using your n4aia04 example for a template. Not too good at the object stuff yet though.

**Comment by gregger2k** [comment]
**FALSE ALARM!!!!**
**I upgraded to the latest ModbusTool at  https://github.com/ClassicDIY/ModbusTool/releases
And all is good!! the write_many completes without error.**

Thanks, Greg

**Comment by gregger2k** [comment]
I figured it out using the functions in the Modbus driver station.toit as an example.
I appreciate the  quality of code and comments in your drivers, tests,  and examples.

**Review by kasperl — APPROVED** [review]
Looks good to me! Nice.

**Pull request merged**
